services:
  redis:
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: cerit.io/ceitec-biodata-pub/gromacs-metadump-api:latest
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATA_FOLDER=/app/data
      - CLEANUP_DAYS=30
      - PREFERRED_URL_SCHEME="http"
      - TZ=Europe/Prague
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/gmxmetadump
    ports:
      - "5000:5000"
    volumes:
      - annotation_data:/app/data
      - database_data:/app/db
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: cerit.io/ceitec-biodata-pub/gromacs-metadump-worker:latest
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATA_FOLDER=/app/data
      - CLEANUP_DAYS=30
      - PREFERRED_URL_SCHEME="http"
      - TZ=Europe/Prague
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/gmxmetadump
    volumes:
      - annotation_data:/app/data
      - database_data:/app/db
    depends_on:
      - redis
      - api
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gmxmetadump
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    volumes:
      - database_data:/var/data/
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_USER=postgres
      - ADMINER_PASSWORD=postgres
      - ADMINER_DB=gmxmetadump
      - ADMINER_PORT=5432
      - ADMINER_HOST=postgres
      - ADMINER_USERNAME=postgres
      - ADMINER_DATABASE=gmxmetadump
    depends_on:
      - postgres

volumes:
  annotation_data:
  database_data:
