apiVersion: v1
kind: Service
metadata:
  name: {{ include "gmd.fullname" . }}-web
spec:
  type: ClusterIP
  selector:
    app: {{ include "gmd.fullname" . }}-web
  ports:
    - port:       {{ .Values.service.web.port | default 8081 }}
      targetPort: {{ .Values.service.web.port | default 8081 }}
