apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gmd.fullname" . }}-web
spec:
  replicas: {{ .Values.replicaCount.web | default 1 }}
  selector:
    matchLabels:
      app: {{ include "gmd.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "gmd.fullname" . }}-web
    spec:
      securityContext:                        # Pod security context
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot:        true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: gmx-metadump-web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          ports:
            - name: frontend-web
              containerPort: {{ .Values.service.web.port | default 8081 }}
              protocol: TCP
          resources:
            requests:
              cpu:    {{ .Values.resources.web.requests.cpu }}
              memory: {{ .Values.resources.web.requests.memory }}
            limits:
              cpu:    {{ .Values.resources.web.limits.cpu }}
              memory: {{ .Values.resources.web.limits.memory }}
          securityContext:                     # Container security context
            runAsUser:                1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL